version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: postgis-db
    environment:
      POSTGRES_USER: almauser
      POSTGRES_PASSWORD: alma4231
      POSTGRES_DB: alma_db
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgis_data:
