services:
  db:
    image: postgis/postgis:15-3.4
    restart: always
    environment:
      POSTGRES_USER: almauser
      POSTGRES_PASSWORD: alma4231
      POSTGRES_DB: alma_db
    ports:
      - "5433:5432"   
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
