services:
  db:
    image: postgis/postgis:17-3.5
    container_name: alma_postgis
    environment:
      POSTGRES_USER: almauser
      POSTGRES_PASSWORD: alma4231
      POSTGRES_DB: alma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
