# Generated by Django 5.2.5 on 2025-09-01 16:08

import ckeditor_uploader.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonustransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция бонусов', 'verbose_name_plural': 'Транзакции бонусов'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адреса доставки'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTP-коды'},
        ),
        migrations.AlterModelOptions(
            name='userbonus',
            options={'verbose_name': 'Бонус пользователя', 'verbose_name_plural': 'Бонусы пользователей'},
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='points',
            field=models.PositiveIntegerField(verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Начислено'), ('spent', 'Потрачено')], max_length=10, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждён'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='house',
            field=models.CharField(max_length=50, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='Shop.deliveryregion', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Регистрация'), ('reset_password', 'Сброс пароля')], default='registration', max_length=20, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userbonus',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
        migrations.AlterField(
            model_name='userbonus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
