# Generated by Django 5.2.5 on 2025-08-26 12:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Только номера Кыргызстана (+996)', max_length=128, null=True, region=None, unique=True),
        ),
    ]
