# Generated by Django 5.2.5 on 2025-09-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
